spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alimentar?serverTimezone=UTC
    username: root
    password: lala123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect    
    hibernate:      
      ddl-auto: update
    generate-ddl: true
    show-sql: true